#!/bin/bash

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
    colorflag="--color"
else # OS X `ls`
    colorflag="-G"
fi

alias ls="ls ${colorflag}"

# List all files colorized in long format
alias ll="ls -l ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -la ${colorflag}"

# Always use color output for `ls`
# Disabled due to problems with command & sudo
#alias ls="command ls ${colorflag}"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# horizontal rule
alias hr='printf —%.0s $(seq $COLUMNS)'

alias g='git grep'

# Typos
alias gti='git'
alias gut='git'
alias got='git'
alias vom='vim'
