#!/bin/bash

UNTRACKED=$(git config --get-color color.status.untracked)
CHANGED=$(git config --get-color color.status.changed)
ADDED=$(git config --get-color color.status.added)
BRANCH=$(git config --get-color color.status.branch)
NOBRANCH=$(git config --get-color color.status.nobranch)
UPSTREAM=$NOBRANCH

if [ "$(git config --bool bash.showUpstream)" == "false" ]; then
    UPSTREAM=
fi

# @todo color branch
# @todo sort upstream config and only if there is a remote

# custom git PS1
__git_ps1_custom() {
    type __git_ps1 >/dev/null 2>&1 && __git_ps1 | awk -v untracked=$UNTRACKED -v changed=$CHANGED -v added=$ADDED -v upstream=$UPSTREAM -v branch=$BRANCH -v nobranch=$NOBRANCH '
    function color(col, str) {
        if (str == "") { str = "&" }
        return "\001" col "\002" str "\001\033[0m\002"
    }
    {
        sub(/%/,     color(untracked))
        sub(/#/,     color(nobranch))
        sub(/\*/,    color(changed))
        sub(/\B\+/,  color(added))
        sub(/<|<?>/, color(upstream))

        if ($0 ~ /([<|=>]|\(\()/) {
            # remove = that means same as upstream
            sub(/=\)/, ")")
        } else if (upstream != "") {
            # add a ^ to signify no upstream
            sub(/\)/, color(nobranch, "^") ")")
        }

        # remove () around detatched refs (tags/shas)
        if (match($0, /\(\([^)]+\)/)) {
            ref = substr($0, RSTART + 2, RLENGTH -3)
            sub(/\(\([^)]+\)/, "(" color(nobranch, ref))
        }

        print
    }'
}

# show '%' for untracked files
export GIT_PS1_SHOWUNTRACKEDFILES=1

# show '*'/'+' for tracked changes. bash.showDirtyState needs this
export GIT_PS1_SHOWDIRTYSTATE=1

# show '<'/'>' for HEAD/upstream diffs. bash.showUpstream needs this
export GIT_PS1_SHOWUPSTREAM=1

export PS1="\[\033[m\]\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$(__git_ps1_custom)\$ "

export PS2="\[\033[0;31m\]→ \[\033[m\]"
