#!/bin/bash

# LS_COLORS
type dircolors >/dev/null 2>&1 && eval $(dircolors)

# default language
export LANG="en_GB.UTF-8"

# grep options
export GREP_OPTIONS="--color=auto"

# MySQL PS1
export MYSQL_PS1="\u@\h:\d> "

# Make vim the default editor
export EDITOR="vim"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# less settings and colours
export LESS="-R"
export LESSCHARSET=utf-8
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;219m' # begin underline

# Larger bash history (allow 32k entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTTIMEFORMAT="%F %T "

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date"

# Hide editor on git merges
export GIT_MERGE_AUTOEDIT="no"
